PreCommit:
  BundleCheck:
    enabled: true
  RuboCop:
    enabled: true
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names', '--rails']
    command: ['bundle', 'exec', 'rubocop'] # Invoke within Bundler context
    exclude:
      - 'db/schema.rb'
      - 'db/seeds.rb'
      - 'db/migrate/*.rb'
  RailsSchemaUpToDate:
    enabled: true
  CoffeeLint:
    enabled: true
PostMerge:
  BundleInstall:
    enabled: true
